### ISSUE TITLE
 Glossary #3 - LASSO - least absolute shrinkage and selection operator

### ISSUE THREAD

**Issue by giangnguyen2412** [giangnguyen2412/InterpretableMLBook-Vietnamese#7]
Em/mình định dịch là: `toán tử lựa chọn và rút gọn tuyệt đối nhỏ nhất`.

LASSO được áp dụng trong nhiều vấn đề kỹ thuật, liệu đã có ai dịch từ này chưa nhỉ?

Mọi người cho ý kiến nhé.

**Comment by hoangnhxda** [comment]
In statistics and machine learning, lasso (least absolute shrinkage and selection operator; also Lasso or LASSO) is a regression analysis method that performs both variable selection and regularization in order to enhance the prediction accuracy and interpretability of the statistical model it produces

Như vậy đây không phải là 1 toán tử mà là 1 thuật toán trong thống kê và ML.
Anh đề xuất dịch là : Thuật toán lựa chọn và rút gọn tối ưu LASSO

**Comment by giangnguyen2412** [comment]
Đồng ý với cách dịch của a @hoangnhxda
